name: hyaena-technologies-web

services:
  htnet-web:
    image: htnet:0.2.0
    ports:
      - "7878:7878/tcp"
            
  dragonfly-key-value:
    image: dragonflydb/dragonfly:v1.27.1
    ports:
      - "8081:8081/tcp"

  grafana-monitoring:
    image: grafana/grafana:12.0.1
    ports:
      - "8082:8082/tcp"

  greptime-time-series:
    image: greptime/greptimedb:v0.14.4
    ports:
      - "8083:8083/tcp"

  greptime-operator:
    image: greptime/greptimedb-operator:v0.3.0
    ports:
      - "8084:8084/tcp"

  greptime-initializer:
    image: greptime/greptimedb-initializer:v0.3.0
    ports:
      - "8085:8085/tcp"

  knative-cli: 
    image: gcr.io/knative-releases/knative.dev/client/cmd/kn:v1.18.0
    ports:
      - "8086:8086/tcp"

  knative-functions: 
    image: ghcr.io/knative/func/func:latest
    ports:
      - "8087:8087/tcp"

  minio-storage:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - "8088:8088/tcp"

  minio-operator:
    image: minio/operator:v7.1.1
    ports:
      - "8089:8089/tcp"

  minio-control:
    image: minio/mc:RELEASE.2025-05-21T01-59-54Z
    ports:
      - "8090:8090/tcp"
  
  spice-authorization:
    image: authzed/spicedb:v1.44.2
    ports:
      - "8091:8091/tcp"
      
  ory-kratos-authentication:
    image: oryd/kratos:v1.3.1
    ports:
      - "8092:8092/tcp"
  
  ory-hydra-oidc:
    image: oryd/hydra:v2.3.0
    ports:
      - "8093:8093/tcp"
  
  spice-operator:
    image: authzed/spicedb-operator:v1.20.1
    ports:
      - "8094:8094/tcp"

  spice-zed:
    image: authzed/zed:v0.30.2
    ports:
      - "8095:8095/tcp"

  surreal-graph:
    image: surrealdb/surrealdb:v2.3.3
    ports:
      - "8096:8096/tcp"

  traefik-proxy:
    image: traefik/traefik:v2.4.9-dyn-buffer
    ports:
      - "8097:8097/tcp"

  vault-secrets:
    image: hashicorp/vault:1.19.5
    ports:
      - "8098:8098/tcp"

