name: hyaena-technologies-web

services:
  htnet-web:
    image: htnet:0.2.0
    ports:
      - "7878:7878/tcp"
            
  dragonfly-key-value:
    image: dragonflydb/dragonfly:v1.27.1
    ports:
      - "8081:8081/tcp"
    
  greptime-time-series:
    image: greptime/greptimedb:v0.14.4
    ports:
      - "8082:8082/tcp"

  greptime-operator:
    image: greptime/greptimedb-operator:v0.3.0
    ports:
      - "8083:8083/tcp"

  greptime-initializer:
    image: greptime/greptimedb-initializer:v0.3.0
    ports:
      - "8084:8084/tcp"

  knative-cli: 
    image: gcr.io/knative-releases/knative.dev/client/cmd/kn:v1.18.0
    ports:
      - "8085:8085/tcp"

  knative-functions: 
    image: ghcr.io/knative/func/func:latest
    ports:
      - "8086:8086/tcp"

  minio-storage:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - "8087:8087/tcp"

  minio-operator:
    image: minio/operator:v7.1.1
    ports:
      - "8088:8088/tcp"

  minio-control:
    image: minio/mc:RELEASE.2025-05-21T01-59-54Z
    ports:
      - "8089:8089/tcp"

  postgres-relational:
    image: postgres:17.5
    ports:
      - "8090:8090/tcp"       
      
  traefik-proxy:
    image: traefik/traefik:v2.4.9-dyn-buffer
    ports:
      - "8096:8091/tcp"

  vault-secrets:
    image: hashicorp/vault:1.19.5
    ports:
      - "8097:8092/tcp"

