apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: distribution-registry
  name: distribution-registry
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: distribution-registry
