apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dolt-relational
  name: dolt-relational
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dolt-relational
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: dolt-relational
    spec:
      containers:
        - image: dolthub/dolt:1.56.0
          name: dolt-relational
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
