apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dragonfly-key-value
  name: dragonfly-key-value
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dragonfly-key-value
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: dragonfly-key-value
    spec:
      containers:
        - image: dragonflydb/dragonfly:latest
          name: dragonfly-key-value
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
