apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: htnet-web
  name: htnet-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: htnet-web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: htnet-web
    spec:
      containers:
        - image: htnet:0.2.0
          name: htnet-web
          ports:
            - containerPort: 7878
              protocol: TCP
      restartPolicy: Always
