apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: knative-cli
  name: knative-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: knative-cli
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: knative-cli
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
          name: knative-cli
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
