apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: knative-functions
  name: knative-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: knative-functions
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: knative-functions
    spec:
      containers:
        - image: ghcr.io/knative/func/func:latest
          name: knative-functions
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
