apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio-control
  name: minio-control
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    io.kompose.service: minio-control
