apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: opentelemetry-collector
  name: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opentelemetry-collector
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: opentelemetry-collector
    spec:
      containers:
        - image: otel/opentelemetry-collector:latest
          name: opentelemetry-collector
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
