apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ory-kratos-authentication
  name: ory-kratos-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ory-kratos-authentication
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ory-kratos-authentication
    spec:
      containers:
        - image: oryd/kratos:v1.3.1
          name: ory-kratos-authentication
          ports:
            - containerPort: 8093
              protocol: TCP
      restartPolicy: Always
