apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ory-hydra-oidc
  name: ory-hydra-oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ory-hydra-oidc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ory-hydra-oidc
    spec:
      containers:
        - image: oryd/hydra:v2.3.0
          name: ory-hydra-oidc
          ports:
            - containerPort: 8094
              protocol: TCP
      restartPolicy: Always
