apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ory-hydra-oidc
  name: ory-hydra-oidc
spec:
  ports:
    - name: "8093"
      port: 8093
      targetPort: 8093
  selector:
    io.kompose.service: ory-hydra-oidc
