apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spice-authorization
  name: spice-authorization
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    io.kompose.service: spice-authorization
