apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spice-operator
  name: spice-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spice-operator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: spice-operator
    spec:
      containers:
        - image: authzed/spicedb-operator:v1.20.1
          name: spice-operator
          ports:
            - containerPort: 8092
              protocol: TCP
      restartPolicy: Always
