apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spice-operator
  name: spice-operator
spec:
  ports:
    - name: "8094"
      port: 8094
      targetPort: 8094
  selector:
    io.kompose.service: spice-operator
