apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: surreal-graph
  name: surreal-graph
spec:
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8096
  selector:
    io.kompose.service: surreal-graph
