apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: traefik-proxy
  name: traefik-proxy
spec:
  ports:
    - name: "8097"
      port: 8097
      targetPort: 8097
  selector:
    io.kompose.service: traefik-proxy
