apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: vault-secrets
  name: vault-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault-secrets
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./compose.yaml -o ./kubernetes
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: vault-secrets
    spec:
      containers:
        - image: hashicorp/vault:1.19.5
          name: vault-secrets
          ports:
            - containerPort: 8097
              protocol: TCP
      restartPolicy: Always
