name: # Project Name

sources: # Path to Sources and Assets
  sourceCode:
    path:	# Path to Source Code: String - *.css, *.html, *.js

  assets:
    path: # Path to Assets: String - *.jpeg, *.png, *.svg, *.webp

port:	# Server Transmission Control Protocol Port: String

